<a href="https://colab.research.google.com/github/Arooj-06/Machine-Learning/blob/main/Day%2034-Data%20and%20Time%20values/Date%20and%20Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
date=pd.read_csv('/content/orders.csv')
time=pd.read_csv('/content/messages.csv')

# DATE AND TIME DATA

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

**VERY IMPORTANT : 1st and important thing to do is , see the date and time are in STRING format and things won't work on them so we hav eto convert them into "DATE AND TIME FORMAT"**



---

# **Working with DATES**

In [7]:
date['date']=pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [ ]:
#now date in converted into the date and time format

**1. EXTRACT YEAR**

In [11]:
date['year']=date['date'].dt.year

In [12]:
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

**2. EXTRACT MONTH**

In [13]:
date['month']=date['date'].dt.month
#using attribute dt.month

In [14]:
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [15]:
date['month_name']=date['date'].dt.month_name()
#use function dt.month_name()

In [16]:
date.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

**3. EXTRACT DAYS**

In [21]:
date['day']=date['date'].dt.day

In [18]:
date.head()

        date  product_id  city_id  orders  year  month month_name  day
0 2019-12-10        5628       25       3  2019     12   December   10
1 2018-08-15        3646       14     157  2018      8     August   15
2 2018-10-23        1859       25       1  2018     10    October   23
3 2019-08-17        7292       25       1  2019      8     August   17
4 2019-01-06        4344       25       3  2019      1    January    6

In [22]:
date['day_name']=date['date'].dt.day_name()

In [23]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday